### ISSUE TITLE
Delete Database

### ISSUE THREAD

**Issue by mnl-assasin** [fallen90/mobile-lms#1]
Wala pang delete database no? 
Pinull ko siya ngayon tapos triny ko yung 

get /files 
may mga laman na siya agad pero wala naman akong files saved.
Pwede bang isaved yung files sa loob nung node project itself (dunno how)

**Comment by fallen90** [comment]
@mnl-assasin delete mo ung `data/db.json` tapos restart mo na lang, automatic naman mag fill up yan ng defaults
